RenanCDev/TraininSync

Documentos/Documento de Visão.md
Adicionei a pasta de documentos do projeto em markdown.
=> docs: add docs folder

Documentos/Documento de Visão.md
Adicionados os códigos e respectivos atores nos requisitos funcionais. Os anteriormente subtópicos, se tornaram RF.
=> Adição dos Códigos e Atores dos RFs

teste.md
Deletei um documento .md não usado.
=> docs: delet unsed Teste.md file

Documentos/Documento de User Stories.md
Fiz a edição do Documento de User Stories de acordo com o Documento de Visão
=> Edição do User Stories

Documentos/Documento de Visão.md
Fixed the Issues relateds at the Vision Document
=> fix: Fixed Issues in Vision Document #07

Documentos/Documento de Visão.md
Fixed Rael's name in the vision document
=> docs:ix team member name in Vision Document

Documentos/Documento de Iteração e Releases.md, traininsync/manage.py
Pull request responding issue #26 and located at the Milestone Iteration 01
=> fix/docs: Added the Iterations and ReleasesDoc.md with base model #26

README.md
Modificações necessárias no readme do projeto
=> docs: fixes inconsistencies in readme file

Documentos/Documento de User Stories.md
Correções no arquivo de User Stories.
=> docs: necessary changes in User Stories file

requirements.txt
Add requirements project.
---
Ex: Closes #36
=> feat: add requirements project

traininSync-back/scripts/p01/create_script.sql, traininSync-back/scripts/p01/inserts_script.sql, traininSync-back/scripts/p01/projeto01-josealvs-q01.sql, traininSync-back/scripts/p01/projeto01-josealvs-q02.sql, traininSync-back/scripts/p01/projeto01-josealvs-q03.sql, traininSync-back/scripts/p01/projeto01.md
Realização de alguns pontos da atividade P01, assim, deixando a parte das consultas individuais para os demais usuários
=> Realização de alguns tópicos da atividade P01 #55

README.md, traininSync-back/scripts/p01/projeto01.md
Adicionei os links que estavam faltando no projeto01.md e no README.md
=> feat: Adicionando links no projeto01.md e README.md #55

traininSync-back/scripts/p01/projeto01-arthurazvd-q01.sql, traininSync-back/scripts/p01/projeto01-arthurazvd-q02.sql
Adicionei os meus scripts referentes a atividade
**Closes #55**
=> feat: add scripts #55

traininSync-back/scripts/p01/projeto01-Gabrielygor-q01.sql, traininSync-back/scripts/p01/projeto01-Gabrielygor-q02.sql, traininSync-back/scripts/p01/projeto01-LuizMiguel4444-q01.sql, traininSync-back/scripts/p01/projeto01-LuizMiguel4444-q02.sql, traininSync-back/scripts/p01/projeto01-RenanCDev-q01.sql, traininSync-back/scripts/p01/projeto01-RenanCDev-q02.sql
=> feat: adiciona os links dos scripts

traininSync-back/setup/settings.py, traininSync-back/setup/urls.py
Add Swagger project.
---
Closes #63
=> feat: add swagger project #63

traininSync-front/index.html, traininSync-front/src/App.tsx, traininSync-front/src/components/button/index.tsx, traininSync-front/src/global.css, traininSync-front/src/main.tsx, traininSync-front/src/pages/register-personal/index.tsx, traininSync-front/src/pages/register/index.tsx, traininSync-front/src/routes/routes.tsx, traininSync-front/src/tailwind.css
Descreva o que foi feito nesse PR:
add register screen, refactor button (add type on props), change site linguage (to prbr) and format some files with the prettier
---
Closes #67
=> feat add register screen

traininSync-back/requirements.txt, traininSync-back/setup/settings.py
Add cors unlock to project.
---
---
Closes #76
=> #76 add cors unlock to project

traininSync-back/traininsync/models.py, traininSync-back/traininsync/serializers.py, traininSync-back/traininsync/templates/api_home.html, traininSync-back/traininsync/urls.py, traininSync-back/traininsync/views.py
Was added the Agenda, RegistrodeProgresso and ContratodeServico Models, togheter withb his Serializer and Views Set. Was added the respective endpoints at django templates too. Some alterations in some rolls from Pessoa.
---
---
closes #80
=> #80: adding missing models (except Pagamento)

traininSync-front/src/pages/register-personal/index.tsx, traininSync-front/src/pages/register-student/index.tsx, traininSync-front/src/routes/routes.tsx
I add the student screen but no link in api (waiting for correction in the back)
Closes #81
=> #81 add student screen

traininSync-back/.pre-commit-config.yaml, traininSync-back/.pylintrc, traininSync-back/isort.cfg, traininSync-front/.pre-commit-config.yaml
Add pré-commit to project.
---
---
Closes #87
=> #87 add pré commit to project

traininSync-front/vercel.json
=> fix: fix vercel deploy

traininSync-front/src/App.tsx, traininSync-front/src/api/payment/createPayment.ts, traininSync-front/src/api/service/createService.ts, traininSync-front/src/components/back-to-top-button/index.tsx, traininSync-front/src/components/navbar/index.tsx, traininSync-front/src/main.tsx, traininSync-front/src/pages/payment/register-payment/index.tsx, traininSync-front/src/pages/payment/register-payment/zod.ts, traininSync-front/src/pages/progress/register-progress/zod.ts, traininSync-front/src/pages/register/index.tsx, traininSync-front/src/pages/register/zod.ts, traininSync-front/src/pages/service/register-service/index.tsx, traininSync-front/src/pages/service/register-service/zod.ts, traininSync-front/src/utils/dinheiro/index.ts
=> #116 refactor navbar

Documentos/Testes de aceitação/gabrielygor_testes_aceitacao-US01.md
Adicionei os testes de aceitação do modulo de personais /personais/
#130
=> feat: adicionei os testes de aceitacao do modulo de personais

Documentos/Testes de aceitação/luizmiguel_testes_aceitacao-US04.md
Adicionei os testes de aceitacao do módulo de contrato de serviço.
---
---
Tudo testado e tudo ok com os resultados dos testes.
---
Closes #133
=> feat: adicionei os testes de aceitacao do módulo de contrato de serviço
